# SPDX-FileCopyrightText: 2026 Samed Yolcu
# SPDX-License-Identifier: GPL-2.0-or-later
#
# License information for files that can't carry an SPDX header.
version = 1

[[annotations]]
path = [
    "README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "docs/**",
    "package.json",
    "package/metadata.json",
    "package/contents/config/main.xml",
    "po/**",
    ".gitignore",
    ".qmllint.ini",
    ".github/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Samed Yolcu"
SPDX-License-Identifier = "GPL-2.0-or-later"
