.pragma library

// SPDX-FileCopyrightText: 2026 Samed Yolcu
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated from po/*.po by scripts/i18n.sh (scripts/po2js.mjs); don't edit.
// Translations used when the widget's language differs from the desktop's.

const CATALOGS = {
    "tr": {
        plural: function (n) { return Number((n > 1)); },
        messages: {
            "@action\u0004Open Today's Note": ["Bugünün Notunu Aç"],
            "@action\u0004Open Vault in Obsidian": ["Kasayı Obsidian'da Aç"],
            "@action\u0004Rescan Vault": ["Kasayı Yeniden Tara"],
            "@action\u0004Year Overview": ["Yıl Özeti"],
            "@action:button\u0004Browse…": ["Göz At…"],
            "@action:button\u0004Choose Vault…": ["Kasa Seç…"],
            "@action:button\u0004Next Month": ["Sonraki Ay"],
            "@action:button\u0004Next Year": ["Sonraki Yıl"],
            "@action:button\u0004Previous Month": ["Önceki Ay"],
            "@action:button\u0004Previous Year": ["Önceki Yıl"],
            "@action:button\u0004This Year": ["Bu Yıl"],
            "@action:button\u0004Year Overview": ["Yıl Özeti"],
            "@action:button reset calendar to today\u0004Today": ["Bugün"],
            "@info\u0004%1 note": ["%1 not","%1 not"],
            "@info\u0004A color too close to the background is made lighter or darker so it stays visible.": ["Arka plana çok yakın bir renk, görünür kalması için açılır ya da koyulaştırılır."],
            "@info\u0004Automatic follows the Calendar plugin or the desktop language. Only matters for formats with month or day names (MMMM, dddd…); the week start isn't affected. Other languages use English names, like Obsidian's default.": ["Otomatik, Calendar eklentisini ya da masaüstü dilini izler. Yalnızca ay ya da gün adı içeren biçimlerde (MMMM, dddd…) önemlidir; hafta başlangıcını etkilemez. Diğer diller, Obsidian'ın varsayılanı gibi İngilizce adları kullanır."],
            "@info\u0004Automatic shows week numbers when “Show week number” is on in the Calendar plugin.": ["Otomatik, Calendar eklentisinde “Show week number” açıksa hafta numaralarını gösterir."],
            "@info\u0004Automatic uses the Calendar plugin's setting, or the desktop's first day of the week.": ["Otomatik, Calendar eklentisinin ayarını ya da masaüstünün haftanın ilk gününü kullanır."],
            "@info\u0004Choose a vault on the General page first.": ["Önce Genel sayfasında bir kasa seçin."],
            "@info\u0004Choose the folder of your Obsidian vault to see your daily notes.": ["Günlük notlarınızı görmek için Obsidian kasanızın klasörünü seçin."],
            "@info\u0004Couldn't open Obsidian. Check that it's installed and handles obsidian:// links.": ["Obsidian açılamadı. Kurulu olduğunu ve obsidian:// bağlantılarını açtığını denetleyin."],
            "@info\u0004Couldn't read the vault": ["Kasa okunamadı"],
            "@info\u0004Current streak: %1 day": ["Güncel seri: %1 gün","Güncel seri: %1 gün"],
            "@info\u0004Enter a path that starts with / or ~/, or use Browse… to choose the folder.": ["/ ya da ~/ ile başlayan bir yol girin veya klasörü seçmek için Göz At… düğmesini kullanın."],
            "@info\u0004Like Plasma's calendar, with word-count dots like the Calendar plugin": ["Plasma takvimi gibi; Calendar eklentisindeki gibi kelime sayısı noktalarıyla"],
            "@info\u0004Like the Calendar plugin: one dot per this many words, up to five. Counts are approximate: frontmatter is skipped and only the beginning of very long notes is read.": ["Calendar eklentisindeki gibi: bu kadar kelime başına bir nokta, en fazla beş. Sayılar yaklaşıktır: ön bilgi (frontmatter) atlanır ve çok uzun notların yalnızca başı okunur."],
            "@info\u0004Longest streak: %1 day": ["En uzun seri: %1 gün","En uzun seri: %1 gün"],
            "@info\u0004Month and day names, dates and the calendar's texts. This settings window always follows the desktop language. The language of note names is set on the Notes page.": ["Ay ve gün adları, tarihler ve takvimin metinleri. Bu ayarlar penceresi her zaman masaüstü dilini kullanır. Not adlarının dili Notlar sayfasında ayarlanır."],
            "@info\u0004No streak yet": ["Henüz seri yok"],
            "@info\u0004No vault selected": ["Kasa seçilmedi"],
            "@info\u0004No weekly notes are configured in Obsidian.": ["Obsidian'da haftalık not ayarı yok."],
            "@info\u0004Not an Obsidian vault": ["Bir Obsidian kasası değil"],
            "@info\u0004Read from the vault saved on the General page. After choosing another vault, apply the change to update this.": ["Genel sayfasında kaydedilen kasadan okunur. Başka bir kasa seçtikten sonra güncellemek için değişikliği uygulayın."],
            "@info\u0004Reading vault…": ["Kasa okunuyor…"],
            "@info\u0004Resize the widget on the desktop by dragging its edges in edit mode.": ["Widget'ı masaüstünde düzenleme kipinde kenarlarından sürükleyerek yeniden boyutlandırın."],
            "@info\u0004The daily notes folder links to a place outside the vault, so it isn't read.": ["Günlük notlar klasörü kasanın dışında bir yere bağlantı veriyor, bu yüzden okunmuyor."],
            "@info\u0004The folder must be inside the vault.": ["Klasör kasanın içinde olmalı."],
            "@info\u0004The vault couldn't be read.": ["Kasa okunamadı."],
            "@info\u0004The vault didn't respond": ["Kasa yanıt vermedi"],
            "@info\u0004The weekly notes folder links to a place outside the vault, so it isn't read.": ["Haftalık notlar klasörü kasanın dışında bir yere bağlantı veriyor, bu yüzden okunmuyor."],
            "@info\u0004The widget only reads the vault. Daily and weekly note settings are taken from Obsidian (core Daily notes, Periodic Notes and Calendar plugins); you can change them on the Notes page.": ["Widget kasayı yalnızca okur. Günlük ve haftalık not ayarları Obsidian'dan alınır (çekirdek Daily notes, Periodic Notes ve Calendar eklentileri); bunları Notlar sayfasından değiştirebilirsiniz."],
            "@info\u0004This format doesn't give a valid file name inside the folder.": ["Bu biçim, klasör içinde geçerli bir dosya adı vermiyor."],
            "@info\u0004Tiles tinted by note length, like an activity heatmap": ["Not uzunluğuna göre renklenen kutucuklar, etkinlik ısı haritası gibi"],
            "@info\u0004Today always opens or creates today's note, with your template when the widget uses Obsidian's own daily note folder and format. Notes created for other days start empty: Obsidian doesn't apply templates to them.": ["Bugün her zaman bugünün notunu açar ya da oluşturur; widget Obsidian'ın kendi günlük not klasörünü ve biçimini kullanıyorsa şablonunuzla. Diğer günler için oluşturulan notlar boş başlar: Obsidian bunlara şablon uygulamaz."],
            "@info\u0004Vault folder not found": ["Kasa klasörü bulunamadı"],
            "@info\u0004Vault path isn't absolute": ["Kasa yolu mutlak değil"],
            "@info\u0004With its own color scheme, the widget draws a background in that scheme's colors.": ["Kendi renk şeması seçildiğinde widget, arka planı o şemanın renkleriyle çizer."],
            "@info %1 folder, %2 format, %3 plugin name\u0004Folder “%1”, format %2, from the %3.": ["Klasör “%1”, biçim %2 (kaynak: %3)."],
            "@info %1 is a date format\u0004The note format “%1” doesn't produce a valid file name.": ["“%1” not biçimi geçerli bir dosya adı üretmiyor."],
            "@info %1 is a file name\u0004%1 has an unexpected structure, so it was ignored.": ["%1 beklenmeyen bir yapıda, bu yüzden yok sayıldı."],
            "@info %1 is a file name\u0004%1 isn't valid JSON, so it was ignored.": ["%1 geçerli bir JSON değil, bu yüzden yok sayıldı."],
            "@info %1 is a file path\u0004Example: %1": ["Örnek: %1"],
            "@info %1 is a folder\u0004The folder “%1” is outside the vault.": ["“%1” klasörü kasanın dışında."],
            "@info %1 is a folder inside the vault\u0004The daily notes folder “%1” doesn't exist yet.": ["Günlük notlar klasörü “%1” henüz yok."],
            "@info %1 is a folder path\u0004%1 doesn't exist or can't be opened.": ["%1 yok ya da açılamıyor."],
            "@info %1 is a folder path\u0004%1 has no .obsidian folder. Choose the vault's top folder.": ["%1 içinde .obsidian klasörü yok. Kasanın en üst klasörünü seçin."],
            "@info %1 is a folder path\u0004Reading %1 took too long. If it's on a network or external drive, check that it's available.": ["%1 okunması çok uzun sürdü. Ağ ya da harici bir sürücüdeyse erişilebilir olduğunu denetleyin."],
            "@info %1 is an error message\u0004Some notes couldn't be listed: %1": ["Bazı notlar listelenemedi: %1"],
            "@info %1 lists date format tokens\u0004The daily note format uses tokens this widget doesn't support: %1": ["Günlük not biçimi, bu widget'ın desteklemediği öğeler kullanıyor: %1"],
            "@info %1 lists date format tokens\u0004The weekly note format uses tokens this widget doesn't support: %1": ["Haftalık not biçimi, bu widget'ın desteklemediği öğeler kullanıyor: %1"],
            "@info %1 lists tokens\u0004Unsupported tokens: %1": ["Desteklenmeyen öğeler: %1"],
            "@info %2 is the formatted number\u0004%2 word": ["%2 kelime","%2 kelime"],
            "@info accessible name, %1 month %2 year\u0004Calendar, %1 %2": ["Takvim, %1 %2"],
            "@info current streak of consecutive days\u0004%1-day streak": ["%1 günlük seri","%1 günlük seri"],
            "@info heatmap legend: longer notes\u0004More": ["Çok"],
            "@info heatmap legend: shorter notes\u0004Less": ["Az"],
            "@info largest value in a chart\u0004max %1": ["en çok %1"],
            "@info notes in the visible month\u0004%1 note": ["%1 not","%1 not"],
            "@info notes in the visible month\u0004%1 note this month": ["Bu ay %1 not","Bu ay %1 not"],
            "@info settings source\u0004Calendar plugin": ["Calendar eklentisi"],
            "@info settings source\u0004Obsidian defaults": ["Obsidian varsayılanları"],
            "@info settings source\u0004Periodic Notes plugin": ["Periodic Notes eklentisi"],
            "@info settings source\u0004core Daily notes plugin": ["çekirdek Daily notes eklentisi"],
            "@info the top folder of the vault\u0004vault root": ["kasa kökü"],
            "@info week number\u0004Week %1": ["%1. hafta"],
            "@info year summary\u0004counting words…": ["kelimeler sayılıyor…"],
            "@info:placeholder\u0004Folder that contains .obsidian": [".obsidian klasörünü içeren klasör"],
            "@info:placeholder\u0004Vault root": ["Kasa kökü"],
            "@info:tooltip\u0004%1-day streak": ["%1 günlük seri","%1 günlük seri"],
            "@info:tooltip\u0004Calendar for Obsidian": ["Obsidian için Takvim"],
            "@info:tooltip\u0004No note": ["Not yok"],
            "@info:tooltip\u0004No note for today yet": ["Bugün için henüz not yok"],
            "@info:tooltip\u0004No note yet": ["Henüz not yok"],
            "@info:tooltip\u0004No weekly note": ["Haftalık not yok"],
            "@info:tooltip\u0004Today's note is written": ["Bugünün notu yazıldı"],
            "@info:tooltip %1 week number, %2 date the week starts\u0004Week %1, from %2": ["%1. hafta, başlangıç: %2"],
            "@info:tooltip a note whose words aren't counted yet\u0004Note": ["Not"],
            "@info:tooltip note path and word count\u0004%2, %1 word": ["%2, %1 kelime","%2, %1 kelime"],
            "@item percentage\u0004%1%": ["%%1"],
            "@item:inlistbox\u0004Creates the note": ["Notu oluşturur"],
            "@item:inlistbox\u0004Does nothing": ["Hiçbir şey yapmaz"],
            "@item:inlistbox\u0004Hide": ["Gizle"],
            "@item:inlistbox\u0004Same as Plasma": ["Plasma ile aynı"],
            "@item:inlistbox\u0004Show": ["Göster"],
            "@item:inlistbox\u0004Vaults Obsidian knows…": ["Obsidian'ın bildiği kasalar…"],
            "@item:inlistbox %1 is a file name\u0004%1 (not found)": ["%1 (bulunamadı)"],
            "@item:inlistbox accent color\u0004Automatic": ["Otomatik"],
            "@item:inlistbox accent color\u0004Custom": ["Özel"],
            "@item:inlistbox background\u0004None": ["Yok"],
            "@item:inlistbox background\u0004Plasma standard": ["Plasma standart"],
            "@item:inlistbox background\u0004Plasma translucent": ["Plasma yarı saydam"],
            "@item:inlistbox background\u0004Solid color, adjustable opacity": ["Düz renk, ayarlanabilir saydamlık"],
            "@item:inlistbox language\u0004System default": ["Sistem varsayılanı"],
            "@item:inlistbox note length\u0004File size": ["Dosya boyutu"],
            "@item:inlistbox note length\u0004Not shown": ["Gösterilmez"],
            "@item:inlistbox note length\u0004Word count": ["Kelime sayısı"],
            "@item:inlistbox note name language\u0004Automatic": ["Otomatik"],
            "@item:inlistbox shape\u0004Circle": ["Daire"],
            "@item:inlistbox shape\u0004Rounded": ["Yuvarlatılmış"],
            "@item:inlistbox shape\u0004Square": ["Kare"],
            "@item:inlistbox spacing\u0004Comfortable": ["Ferah"],
            "@item:inlistbox spacing\u0004Compact": ["Sıkı"],
            "@item:inlistbox spacing\u0004Normal": ["Normal"],
            "@item:inlistbox week numbers\u0004Automatic": ["Otomatik"],
            "@item:inlistbox week start\u0004Automatic": ["Otomatik"],
            "@item:valuesuffix\u0004%1 second": ["%1 saniye","%1 saniye"],
            "@label\u0004Accent color:": ["Vurgu rengi:"],
            "@label\u0004Design:": ["Tasarım:"],
            "@label\u0004Detected:": ["Algılanan:"],
            "@label\u0004Show:": ["Göster:"],
            "@label:listbox\u0004Background:": ["Arka plan:"],
            "@label:listbox\u0004Clicking a day without a note:": ["Notu olmayan bir güne tıklamak:"],
            "@label:listbox\u0004Color scheme:": ["Renk şeması:"],
            "@label:listbox\u0004Day shape:": ["Gün şekli:"],
            "@label:listbox\u0004Language of note names:": ["Not adlarının dili:"],
            "@label:listbox\u0004Language:": ["Dil:"],
            "@label:listbox\u0004Note length shown by:": ["Not uzunluğu gösterimi:"],
            "@label:listbox\u0004Or pick a vault:": ["Ya da bir kasa seçin:"],
            "@label:listbox\u0004Spacing:": ["Boşluk:"],
            "@label:listbox\u0004Week numbers:": ["Hafta numaraları:"],
            "@label:listbox\u0004Week starts on:": ["Hafta başlangıcı:"],
            "@label:slider\u0004Background opacity:": ["Arka plan matlığı:"],
            "@label:slider\u0004Text size:": ["Yazı boyutu:"],
            "@label:spinbox\u0004Check for new notes every:": ["Yeni notları denetleme sıklığı:"],
            "@label:spinbox\u0004Words per dot:": ["Nokta başına kelime:"],
            "@label:textbox\u0004Folder:": ["Klasör:"],
            "@label:textbox\u0004Format:": ["Biçim:"],
            "@label:textbox\u0004Vault folder:": ["Kasa klasörü:"],
            "@option:check\u0004From the Calendar plugin": ["Calendar eklentisinden"],
            "@option:check\u0004Notes this month and current streak": ["Bu ayki notlar ve güncel seri"],
            "@option:check\u0004Today's date next to the panel icon": ["Panel simgesinin yanında bugünün tarihi"],
            "@option:check\u0004Use ISO 8601 week numbers": ["ISO 8601 hafta numaralarını kullan"],
            "@option:check\u0004Use a different folder and format": ["Farklı klasör ve biçim kullan"],
            "@option:radio chart values\u0004Notes": ["Notlar"],
            "@option:radio chart values\u0004Words": ["Kelimeler"],
            "@option:radio design\u0004Journal": ["Günce"],
            "@option:radio design\u0004Plasma Native": ["Plasma Yerel"],
            "@title\u0004Appearance": ["Görünüm"],
            "@title\u0004Calendar": ["Takvim"],
            "@title\u0004General": ["Genel"],
            "@title\u0004Notes": ["Notlar"],
            "@title\u0004Notes per Month and Week": ["Aylara ve Haftalara Göre Notlar"],
            "@title\u0004Words per Month and Week": ["Aylara ve Haftalara Göre Kelimeler"],
            "@title chart\u0004Per ISO week": ["ISO haftalarına göre"],
            "@title chart\u0004Per month": ["Aylara göre"],
            "@title month and year, e.g. March 2025\u0004%1 %2": ["%1 %2"],
            "@title:group\u0004Colors": ["Renkler"],
            "@title:group\u0004Daily notes": ["Günlük notlar"],
            "@title:group\u0004Names and clicks": ["Adlar ve tıklamalar"],
            "@title:group\u0004Notes on the calendar": ["Takvimdeki notlar"],
            "@title:group\u0004Size": ["Boyut"],
            "@title:group\u0004Weekly notes": ["Haftalık notlar"],
            "@title:window\u0004Choose Accent Color": ["Vurgu Rengi Seç"],
            "@title:window\u0004Choose Obsidian Vault": ["Obsidian Kasası Seç"],
            "@title:window\u0004Year Overview": ["Yıl Özeti"]
        }
    }
};
